/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ViewPlusPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");
var import_promises = require("fs/promises");
var import_path2 = require("path");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  showHiddenFiles: true,
  showUnsupportedFiles: true,
  excludePatterns: [".git/**", "!.git/config"]
};
var ViewPlusSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "View Plus Settings" });
    new import_obsidian.Setting(containerEl).setName("Show hidden files and folders").setDesc(
      "Display dotfiles and dotfolders (e.g. .gitignore, .env, .github/) in the file explorer. Requires plugin reload to fully take effect. Large dot-folders (e.g. .git) may cause a temporary freeze on first scan."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showHiddenFiles).onChange(async (value) => {
        this.plugin.settings.showHiddenFiles = value;
        await this.plugin.saveSettings();
        if (value) {
          this.plugin.applyHiddenFilesPatch();
        } else {
          this.plugin.removeHiddenFilesPatch();
          new import_obsidian.Notice(
            "View Plus: Hidden files hidden. Restart Obsidian to remove them from the file explorer."
          );
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show unsupported file types").setDesc(
      "Display files with extensions Obsidian doesn't natively support (e.g. .py, .js, .json, .csv, .zip). Uses Obsidian's built-in 'showUnsupportedFiles' vault config setting."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showUnsupportedFiles).onChange(async (value) => {
        this.plugin.settings.showUnsupportedFiles = value;
        await this.plugin.saveSettings();
        this.plugin.applyUnsupportedFilesSetting(value);
      })
    );
    new import_obsidian.Setting(containerEl).setName("Exclude patterns").setDesc(
      "One pattern per line. Supports * (within a segment) and ** (across segments). Use ! prefix to negate. Patterns without / match the filename at any depth. Examples: *.log  .env*  .git/**  !.git/config  **/vendor"
    ).addTextArea((text) => {
      text.setPlaceholder(".git/**\n!.git/config").setValue(this.plugin.settings.excludePatterns.join("\n")).onChange((value) => {
        clearTimeout(this.excludeDebounceTimer);
        this.excludeDebounceTimer = setTimeout(async () => {
          this.plugin.settings.excludePatterns = value.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
          await this.plugin.saveSettings();
        }, 300);
      });
      text.inputEl.rows = 8;
      text.inputEl.cols = 40;
      text.inputEl.style.width = "100%";
      text.inputEl.style.fontFamily = "var(--font-monospace)";
    });
  }
};

// src/viewer.ts
var import_obsidian2 = require("obsidian");
var import_path = require("path");
var FILE_VIEWER_VIEW_TYPE = "view-plus-file-viewer";
var MEDIA_VIEWER_VIEW_TYPE = "view-plus-media-viewer";
var MAX_FILE_SIZE = 500 * 1024;
var MAX_TABLE_ROWS = 5e3;
var IMAGE_EXTS = /* @__PURE__ */ new Set(["avif", "ico", "tiff", "tif"]);
var AUDIO_EXTS = /* @__PURE__ */ new Set(["aac", "opus"]);
var VIDEO_EXTS = /* @__PURE__ */ new Set(["mov", "avi", "mkv", "wmv", "m4v"]);
var MEDIA_EXTENSIONS = [
  ...IMAGE_EXTS,
  ...AUDIO_EXTS,
  ...VIDEO_EXTS
];
function openWithSystemApp(app, file) {
  const basePath = app.vault.adapter.getBasePath();
  const absPath = (0, import_path.join)(basePath, file.path);
  const { shell } = require("electron");
  shell.openPath(absPath).then((err) => {
    if (err) console.error("View Plus: openPath failed", err);
  });
}
var FileViewerView = class extends import_obsidian2.TextFileView {
  constructor(leaf) {
    super(leaf);
    this.renderSeq = 0;
    this.addAction("external-link", "Open with system app", () => {
      if (this.file) openWithSystemApp(this.app, this.file);
    });
  }
  getViewType() {
    return FILE_VIEWER_VIEW_TYPE;
  }
  getIcon() {
    var _a, _b, _c;
    const ext = (_c = (_b = (_a = this.file) == null ? void 0 : _a.extension) == null ? void 0 : _b.toLowerCase()) != null ? _c : "";
    if (ext === "csv" || ext === "tsv") return "table";
    return "file-code";
  }
  getDisplayText() {
    var _a, _b;
    return (_b = (_a = this.file) == null ? void 0 : _a.name) != null ? _b : "View Plus";
  }
  getViewData() {
    return this.data;
  }
  setViewData(data, _clear) {
    this.data = data;
    this.renderContent(data).catch((e) => {
      console.error("View Plus: renderContent failed", e);
    });
  }
  clear() {
    this.renderSeq++;
    this.data = "";
    this.contentEl.empty();
    this.contentEl.removeClass("view-plus-viewer");
  }
  async renderContent(content) {
    var _a, _b, _c, _d, _e;
    const seq = ++this.renderSeq;
    this.contentEl.empty();
    this.contentEl.removeClass("view-plus-viewer");
    const ext = (_c = (_b = (_a = this.file) == null ? void 0 : _a.extension) == null ? void 0 : _b.toLowerCase()) != null ? _c : "";
    if (ext === "csv" || ext === "tsv") {
      renderCsvTable(this.contentEl, content, ext === "tsv" ? "	" : ",");
      return;
    }
    this.contentEl.addClass("view-plus-viewer");
    if (content.length > MAX_FILE_SIZE) {
      this.contentEl.createEl("p", {
        cls: "view-plus-too-large",
        text: `File too large to preview (${Math.round(content.length / 1024)} KB).`
      });
      return;
    }
    const lang = extensionToLanguage(ext);
    const markdown = "```" + lang + "\n" + content + "\n```";
    const temp = document.createElement("div");
    await import_obsidian2.MarkdownRenderer.render(
      this.app,
      markdown,
      temp,
      (_e = (_d = this.file) == null ? void 0 : _d.path) != null ? _e : "",
      this
    );
    if (seq !== this.renderSeq) return;
    this.contentEl.empty();
    this.contentEl.append(...Array.from(temp.childNodes));
  }
};
var MediaView = class extends import_obsidian2.FileView {
  constructor(leaf) {
    super(leaf);
    this.addAction("external-link", "Open with system app", () => {
      if (this.file) openWithSystemApp(this.app, this.file);
    });
  }
  getViewType() {
    return MEDIA_VIEWER_VIEW_TYPE;
  }
  getDisplayText() {
    var _a, _b;
    return (_b = (_a = this.file) == null ? void 0 : _a.name) != null ? _b : "View Plus";
  }
  getIcon() {
    var _a, _b, _c;
    const ext = (_c = (_b = (_a = this.file) == null ? void 0 : _a.extension) == null ? void 0 : _b.toLowerCase()) != null ? _c : "";
    if (AUDIO_EXTS.has(ext)) return "music";
    if (VIDEO_EXTS.has(ext)) return "film";
    return "image";
  }
  async onLoadFile(file) {
    this.contentEl.empty();
    this.contentEl.addClass("view-plus-media");
    const ext = file.extension.toLowerCase();
    const resourcePath = this.app.vault.adapter.getResourcePath(
      file.path
    );
    if (IMAGE_EXTS.has(ext)) {
      const wrap = this.contentEl.createDiv({ cls: "view-plus-media-image-wrap" });
      const img = wrap.createEl("img", {
        attr: { src: resourcePath },
        cls: "view-plus-media-image"
      });
      img.addEventListener("error", () => renderCannotPreview(wrap));
    } else if (AUDIO_EXTS.has(ext)) {
      const wrap = this.contentEl.createDiv({
        cls: "view-plus-media-audio-wrap"
      });
      wrap.createEl("p", {
        text: file.name,
        cls: "view-plus-media-label"
      });
      const audio = wrap.createEl("audio", {
        cls: "view-plus-media-audio"
      });
      audio.src = resourcePath;
      audio.controls = true;
      audio.addEventListener(
        "error",
        () => renderCannotPreview(wrap)
      );
    } else if (VIDEO_EXTS.has(ext)) {
      const wrap = this.contentEl.createDiv({
        cls: "view-plus-media-video-wrap"
      });
      const video = wrap.createEl("video", {
        cls: "view-plus-media-video"
      });
      video.src = resourcePath;
      video.controls = true;
      video.addEventListener(
        "error",
        () => renderCannotPreview(wrap)
      );
    }
  }
  async onUnloadFile(_file) {
    this.contentEl.empty();
  }
};
function renderCannotPreview(container) {
  container.empty();
  container.createEl("p", {
    cls: "view-plus-cannot-preview",
    text: 'Cannot preview this file in Obsidian. Use the "Open with system app" button above.'
  });
}
function renderCsvTable(containerEl, content, delimiter) {
  var _a, _b;
  const rows = parseCsv(content, delimiter);
  if (rows.length === 0) {
    containerEl.createEl("p", {
      text: "Empty file.",
      cls: "view-plus-too-large"
    });
    return;
  }
  const truncated = rows.length > MAX_TABLE_ROWS + 1;
  const displayRows = truncated ? rows.slice(0, MAX_TABLE_ROWS + 1) : rows;
  const colCount = Math.max(...displayRows.map((r) => r.length));
  const outer = containerEl.createDiv({ cls: "view-plus-csv-container" });
  const wrap = outer.createDiv({ cls: "view-plus-table-wrap" });
  const table = wrap.createEl("table", { cls: "view-plus-table" });
  const thead = table.createEl("thead");
  const headerRow = thead.createEl("tr");
  for (let i = 0; i < colCount; i++) {
    headerRow.createEl("th", { text: (_a = displayRows[0][i]) != null ? _a : "" });
  }
  const tbody = table.createEl("tbody");
  for (const row of displayRows.slice(1)) {
    const tr = tbody.createEl("tr");
    for (let i = 0; i < colCount; i++) {
      tr.createEl("td", { text: (_b = row[i]) != null ? _b : "" });
    }
  }
  if (truncated) {
    outer.createEl("p", {
      cls: "view-plus-table-truncated",
      text: `Showing first ${MAX_TABLE_ROWS.toLocaleString()} of ${(rows.length - 1).toLocaleString()} rows.`
    });
  }
}
function parseCsv(content, delimiter) {
  const rows = [];
  let current = [];
  let field = "";
  let inQuotes = false;
  let i = 0;
  while (i < content.length) {
    const ch = content[i];
    if (inQuotes) {
      if (ch === '"') {
        if (content[i + 1] === '"') {
          field += '"';
          i += 2;
          continue;
        }
        inQuotes = false;
      } else {
        field += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === delimiter) {
      current.push(field);
      field = "";
    } else if (ch === "\n") {
      current.push(field);
      field = "";
      rows.push(current);
      current = [];
    } else if (ch !== "\r") {
      field += ch;
    }
    i++;
  }
  if (current.length > 0 || field !== "") {
    current.push(field);
    if (current.some((f) => f !== "")) rows.push(current);
  }
  return rows;
}
var TEXT_EXTENSIONS = [
  // Web / scripting
  "js",
  "mjs",
  "cjs",
  "ts",
  "jsx",
  "tsx",
  "py",
  "rb",
  "php",
  "go",
  "rs",
  "c",
  "h",
  "cpp",
  "hpp",
  "java",
  "kt",
  "swift",
  // Config / data
  "json",
  "yaml",
  "yml",
  "toml",
  "ini",
  "cfg",
  "conf",
  "properties",
  "env",
  "gitignore",
  "gitconfig",
  "gitattributes",
  "editorconfig",
  "dockerignore",
  "lock",
  // Styles / markup
  "css",
  "scss",
  "sass",
  "less",
  "html",
  "htm",
  "xml",
  // Shell
  "sh",
  "bash",
  "zsh",
  "fish",
  "ps1",
  // Query / data
  "sql",
  "csv",
  "tsv",
  // Misc text
  "txt",
  "log",
  "diff",
  "patch"
];
function extensionToLanguage(ext) {
  var _a;
  const map = {
    js: "javascript",
    mjs: "javascript",
    cjs: "javascript",
    ts: "typescript",
    jsx: "javascript",
    tsx: "typescript",
    py: "python",
    rb: "ruby",
    php: "php",
    go: "go",
    rs: "rust",
    c: "c",
    h: "c",
    cpp: "cpp",
    hpp: "cpp",
    java: "java",
    kt: "kotlin",
    swift: "swift",
    json: "json",
    yaml: "yaml",
    yml: "yaml",
    toml: "toml",
    ini: "ini",
    cfg: "ini",
    conf: "ini",
    properties: "ini",
    env: "bash",
    gitignore: "bash",
    gitattributes: "ini",
    gitconfig: "ini",
    editorconfig: "ini",
    dockerignore: "bash",
    css: "css",
    scss: "scss",
    sass: "sass",
    less: "less",
    html: "html",
    htm: "html",
    xml: "xml",
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    fish: "fish",
    ps1: "powershell",
    sql: "sql",
    diff: "diff",
    patch: "diff",
    lock: "yaml",
    log: "",
    txt: ""
  };
  return (_a = map[ext.toLowerCase()]) != null ? _a : ext;
}

// src/main.ts
var ViewPlusPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.patchApplied = false;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ViewPlusSettingTab(this.app, this));
    this.registerView(FILE_VIEWER_VIEW_TYPE, (leaf) => new FileViewerView(leaf));
    this.registerExtensions(TEXT_EXTENSIONS, FILE_VIEWER_VIEW_TYPE);
    this.registerView(MEDIA_VIEWER_VIEW_TYPE, (leaf) => new MediaView(leaf));
    this.registerExtensions(MEDIA_EXTENSIONS, MEDIA_VIEWER_VIEW_TYPE);
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (!(file instanceof import_obsidian3.TFile) || file.extension === "md") return;
        menu.addItem(
          (item) => item.setTitle("Open with system app").setIcon("external-link").onClick(() => openWithSystemApp(this.app, file))
        );
      })
    );
    this.addCommand({
      id: "open-with-system-app",
      name: "Open with system app",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file || file.extension === "md") return false;
        if (!checking) openWithSystemApp(this.app, file);
        return true;
      }
    });
    this.registerDomEvent(document, "dblclick", (evt) => {
      const navTitle = evt.target.closest(
        ".nav-file-title"
      );
      if (!navTitle) return;
      const filePath = navTitle.getAttribute("data-path");
      if (!filePath) return;
      const file = this.app.vault.getFileByPath(filePath);
      if (!file || file.extension === "md") return;
      openWithSystemApp(this.app, file);
    });
    this.app.workspace.onLayoutReady(() => {
      this.applyUnsupportedFilesSetting(this.settings.showUnsupportedFiles);
      if (this.settings.showHiddenFiles) {
        this.applyHiddenFilesPatch();
      }
    });
  }
  onunload() {
    this.removeHiddenFilesPatch();
    this.applyUnsupportedFilesSetting(false);
  }
  applyUnsupportedFilesSetting(enabled) {
    this.app.vault.setConfig("showUnsupportedFiles", enabled);
  }
  applyHiddenFilesPatch() {
    var _a;
    if (this.patchApplied) return;
    const adapter = this.app.vault.adapter;
    if (typeof adapter.reconcileDeletion !== "function" || typeof adapter.reconcileFile !== "function" || typeof adapter.getBasePath !== "function") {
      new import_obsidian3.Notice(
        "View Plus: 'Show hidden files' is only supported on desktop. This feature will be disabled."
      );
      return;
    }
    this.originalReconcileDeletion = adapter.reconcileDeletion.bind(adapter);
    const plugin = this;
    adapter.reconcileDeletion = async function(normalizedPath, isFolder) {
      if (plugin.settings.showHiddenFiles && isDotName(normalizedPath) && !isExcluded(normalizedPath, plugin.settings.excludePatterns)) {
        try {
          await this.reconcileFile(normalizedPath, isFolder);
        } catch (e) {
          await plugin.originalReconcileDeletion.call(
            this,
            normalizedPath,
            isFolder
          );
        }
        return;
      }
      await plugin.originalReconcileDeletion.call(
        this,
        normalizedPath,
        isFolder
      );
    };
    this.patchApplied = true;
    (_a = this.discoveryController) == null ? void 0 : _a.abort();
    this.discoveryController = new AbortController();
    this.discoverHiddenFiles("", this.discoveryController.signal).catch((e) => {
      console.error("View Plus: discoverHiddenFiles failed", e);
    });
  }
  async discoverHiddenFiles(relPath, signal, depth = 0, inSymlinkedTree = false) {
    if (depth > 25 || signal.aborted) return;
    const adapter = this.app.vault.adapter;
    const basePath = adapter.getBasePath();
    const absPath = relPath ? (0, import_path2.join)(basePath, relPath) : basePath;
    let entries;
    try {
      entries = await (0, import_promises.readdir)(absPath, { withFileTypes: true });
    } catch (e) {
      return;
    }
    if (signal.aborted) return;
    const regularDirs = [];
    const symlinkDirs = [];
    await Promise.all(
      entries.map(async (entry) => {
        if (signal.aborted) return;
        const childRelPath = relPath ? `${relPath}/${entry.name}` : entry.name;
        let isDir = entry.isDirectory();
        const isSymlink = entry.isSymbolicLink();
        if (isSymlink) {
          try {
            isDir = (await (0, import_promises.stat)((0, import_path2.join)(basePath, childRelPath))).isDirectory();
          } catch (e) {
            return;
          }
        }
        if (isExcluded(childRelPath, this.settings.excludePatterns)) return;
        if (inSymlinkedTree || isSymlink || entry.name.startsWith(".")) {
          try {
            await adapter.reconcileFile(childRelPath, isDir);
          } catch (e) {
          }
        }
        if (isDir) {
          if (isSymlink) {
            symlinkDirs.push(childRelPath);
          } else {
            regularDirs.push(childRelPath);
          }
        }
      })
    );
    for (const dir of regularDirs) {
      if (signal.aborted) return;
      await this.discoverHiddenFiles(dir, signal, depth, inSymlinkedTree);
    }
    for (const dir of symlinkDirs) {
      if (signal.aborted) return;
      await this.discoverHiddenFiles(dir, signal, depth + 1, true);
    }
  }
  removeHiddenFilesPatch() {
    var _a;
    (_a = this.discoveryController) == null ? void 0 : _a.abort();
    this.discoveryController = void 0;
    if (!this.patchApplied || !this.originalReconcileDeletion) return;
    const adapter = this.app.vault.adapter;
    adapter.reconcileDeletion = this.originalReconcileDeletion;
    this.patchApplied = false;
    this.originalReconcileDeletion = void 0;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!Array.isArray(this.settings.excludePatterns)) {
      this.settings.excludePatterns = DEFAULT_SETTINGS.excludePatterns;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function isDotName(normalizedPath) {
  const segments = normalizedPath.split("/");
  const name = segments[segments.length - 1];
  return name.startsWith(".") && name !== "." && name !== "..";
}
function isExcluded(normalizedPath, patterns) {
  let excluded = false;
  for (const pattern of patterns) {
    if (pattern.startsWith("!")) {
      if (matchesPattern(normalizedPath, pattern.slice(1))) excluded = false;
    } else {
      if (matchesPattern(normalizedPath, pattern)) excluded = true;
    }
  }
  return excluded;
}
function globToRegexSrc(pattern) {
  return pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "\0").replace(/\*/g, "[^/]*").replace(/\x00\//g, "(?:[^/]+/)*").replace(/\/\x00/g, "(?:/.*)?").replace(/\x00/g, ".*");
}
function matchesPattern(path, pattern) {
  const hasSlash = pattern.includes("/");
  if (hasSlash) {
    return new RegExp(`^${globToRegexSrc(pattern)}$`).test(path);
  }
  const re = new RegExp(`^${globToRegexSrc(pattern)}$`);
  return path.split("/").some((seg) => re.test(seg));
}
